import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { AuthSession } from "@/provider/AuthSession";

const onest = localFont({
  src: "./fonts/Onest-VariableFont_wght.ttf",
  variable: "--font-onest",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} antialiased`}>
        <AuthSession>{children}</AuthSession>
      </body>
    </html>
  );
}
